name: Sonar
on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types: 
      - completed
jobs:
  sonar:
    name: Sonar
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:  
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          repository: 'adobe/aem-spa-project-core'
          ref: 'master'
          fetch-depth: 0
      - name: Upload Sonar report to sonarcloud.io and comment in pull request
        run: mvn -B verify sonar:sonar -Dsonar.coverage.jacoco.xmlReportPaths=../core/target/site/jacoco/jacoco.xml -Dsonar.organization=adobeinc -Dsonar.projectKey=adobe_aem-spa-project-core -Dsonar.login=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
